name: schaccs
description: "A new Flutter project."
# Prevent accidental publishing:
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Charts package (requires intl <0.18.0)
  charts_flutter: ^0.12.0

  # Firebase & state management
  firebase_core: ^2.5.0
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.16.0
  provider: ^6.0.5
  connectivity_plus: ^5.0.2

  # Date formatting (matched to charts_flutter’s constraint)
  intl: ^0.17.0

  # CSV export
  csv: ^5.0.2

  # PDF generation
  pdf: ^3.8.4

  # Open files
  open_filex: ^4.3.2

  # URL launcher
  url_launcher: ^6.1.10

  # File system paths
  path_provider: ^2.0.15

  # Icons
  cupertino_icons: ^1.0.8
  printing: ^5.14.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0
   # File picker and Excel processing
  file_picker: ^8.0.0+1
  excel: ^4.0.3
  fl_chart: ^1.0.0
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # App icon generator
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "src/Capture.PNG"

flutter:
  uses-material-design: true
